workflows:
  ios:
    name: iOS Build Workflow
    max_build_duration: 60  # Duración máxima de la construcción en minutos
    environment:
      vars:
        CUSTOM_ENV_VAR: "value"  # Opcional: puedes agregar variables de entorno
    scripts:
      # Paso 1: Instalar CocoaPods y dependencias
      - name: Install CocoaPods and dependencies
        script: |
          # Instalar RVM (Ruby Version Manager)
          curl -sSL https://get.rvm.io | bash -s stable --ruby
          # Instalar CocoaPods (versión compatible para tu proyecto)
          gem install cocoapods -v 1.11.2
          # Instalar dependencias definidas en Podfile (para iOS)
          pod install
          
      # Paso 2: Construir el proyecto de iOS
      - name: Build the iOS project
        script: |
          ./gradlew build

      # Paso 3: Ejecutar pruebas (si tienes pruebas configuradas)
      - name: Run tests
        script: |
          ./gradlew test

    artifacts:
      # Guardar el archivo .ipa generado después de la compilación
      - build/iosApp/build/outputs/*.ipa  # El archivo IPA para distribución

  android:
    name: Android Build Workflow
    environment:
      vars:
        CUSTOM_ENV_VAR: "value"
    scripts:
      # Paso 1: Construir el proyecto Android
      - name: Build Android app
        script: |
          ./gradlew clean build

    artifacts:
      # Guardar el archivo APK generado
      - build/app/outputs/**/*.apk  # El APK generado para Android
