workflows:
  ios:
    name: iOS Build Workflow
    max_build_duration: 60  # Duración máxima de la construcción en minutos
    environment:
      vars:
        CUSTOM_ENV_VAR: "value"  # Opcional: puedes agregar variables de entorno
    scripts:
      # Instalar dependencias necesarias
      - name: Install CocoaPods and dependencies
        script: |
          curl -sSL https://get.rvm.io | bash -s stable --ruby
          gem install cocoapods
          pod install
      # Comando para construir el proyecto
      - name: Build the project
        script: |
          ./gradlew build
      # Ejecución de pruebas
      - name: Run tests
        script: |
          ./gradlew test
    artifacts:
      # Especifica el archivo IPA generado
      - build/iosApp/build/outputs/*.ipa  # El archivo IPA que se generará

  android:
    name: Android Build Workflow
    platform: android
    environment:
      vars:
        CUSTOM_ENV_VAR: "value"
    scripts:
      # Construir el proyecto Android
      - name: Build Android app
        script: |
          ./gradlew clean build
    artifacts:
      - build/app/outputs/**/*.apk  # El APK generado
